import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";
import SideBar from "@/components/layout/sidebar/SideBar";
import PostContextProvider from "@/contexts/PostContext";
import UserContextProvider from "@/contexts/UserContext";

export const metadata: Metadata = {
  title: "Dummy Instagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" flex flex-col  items-center pb-16">
        <UserContextProvider>
          <Header />
          <SideBar />
          <PostContextProvider>{children}</PostContextProvider>
          <Footer />
        </UserContextProvider>
      </body>
    </html>
  );
}
